### ISSUE TITLE
fatal error: opencv2/cudaimgproc.hpp: No such file or directory

### ISSUE THREAD

**Issue by anl13** [yuanxy92/GenCameraDriver#1]
When I compile master branch in Ubuntu16.04, I come up with error: 
`fatal error: opencv2/cudaimgproc.hpp: No such file or directory` 
My opencv version is `2.4.9`. 

Full output of make: 
```shell
al17@al17-All-Series:~/project_multicam/GenCameraDriver/build$ make 
Scanning dependencies of target GenCameraDriver
[ 12%] Building CXX object CMakeFiles/GenCameraDriver.dir/PointGrey/PointGreyCamera.cpp.o
In file included from /home/al17/project_multicam/GenCameraDriver/RealCameraDriver.h:15:0,
                 from /home/al17/project_multicam/GenCameraDriver/PointGrey/PointGreyCamera.h:21,
                 from /home/al17/project_multicam/GenCameraDriver/PointGrey/PointGreyCamera.cpp:8:
/home/al17/project_multicam/GenCameraDriver/NPPJpegCoder.h:16:35: fatal error: opencv2/cudaimgproc.hpp: No such file or directory
compilation terminated.
CMakeFiles/GenCameraDriver.dir/build.make:62: recipe for target 'CMakeFiles/GenCameraDriver.dir/PointGrey/PointGreyCamera.cpp.o' failed
make[2]: *** [CMakeFiles/GenCameraDriver.dir/PointGrey/PointGreyCamera.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/GenCameraDriver.dir/all' failed
make[1]: *** [CMakeFiles/GenCameraDriver.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

How to solve it? 

Or which branch should I use for ubuntu?

**Comment by zhu-ty** [comment]
pls make sure that you are using cuda9.1 & opencv3.4.0
also, make sure that the cuda support is enabled when compiling the opencv source code

**Comment by zhu-ty** [comment]
also any branch (master/ScaleableCoding/MixCamera) is OK for you to use.

**Comment by Aashish75** [comment]
I am also getting the same error- fatal error: opencv2/cudaimgproc.hpp: No such file or directory
 #include <opencv2/cudaimgproc.hpp>. I am using colab and it has opencv4 preinstalled. I tried to change it to 3.4 by running !pip install opencv-contrib-python==3.4.2.17 --force-reinstall. It has CUDA 10. I still get the same error. Please help.

**Comment by yuanxy92** [comment]
@Aashish75 sorry for reply late. We build OpenCV and OpenCV-contrib using VS2015. We haven't tasted it using pre-build libraries.
