### ISSUE TITLE
CMakeLists.txt line 153 'cuda' dir not exist

### ISSUE THREAD

**Issue by anl13** [yuanxy92/GenCameraDriver#2]
In master branch, `CMakeLists.txt` line 153, 

```Makefile
source_group("cuda" FILES
    cuda/NPPJpegCoderKernel.h
    cuda/NPPJpegCoderKernel.cu
)
```
But in source dir, there is no `cuda` directory. May be the `CMakeLists.txt` need update?

**Comment by zhu-ty** [comment]
Oops, that's a mistake, a new commit has been uploaded, or you can use ScalableCoding branch.
