### ISSUE TITLE
 Compression in Jetson TX2

### ISSUE THREAD

**Issue by cpaniagua1** [yuanxy92/GenCameraDriver#4]
Hello,

I have 7 point grey cameras and a Jetson TX2 (Ubuntu 16.04). I would like to compress and stream them through a wifi connection. 
Is it possible to use this software for this task?

Thank you!

**Comment by zhu-ty** [comment]
well this repository does not have function for Internet streaming, and the images will only be compressed by JPEG (which is super large compared to video based coding method).
However if you write your own network streaming functions it's OK to use this repo.
